/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppPolicyRouteImport } from './routes/_app/policy'
import { Route as AppViewsRouteImport } from './routes/_app/views'
import { Route as AppIssuesIndexRouteImport } from './routes/_app/issues/index'
import { Route as AppIssuesIssueIdRouteImport } from './routes/_app/issues/$issueId'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AppTeamsTeamIdRouteImport } from './routes/_app/teams/$teamId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyRoute = AppPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AppRoute,
} as any)
const AppViewsRoute = AppViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesIndexRoute = AppIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesIssueIdRoute = AppIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/inbox': typeof AppInboxRoute
  '/policy': typeof AppPolicyRoute
  '/views': typeof AppViewsRoute
  '/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/issues/': typeof AppIssuesIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/teams/': typeof AppTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/inbox': typeof AppInboxRoute
  '/policy': typeof AppPolicyRoute
  '/views': typeof AppViewsRoute
  '/': typeof AppIndexRoute
  '/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/issues': typeof AppIssuesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/teams': typeof AppTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/inbox': typeof AppInboxRoute
  '/_app/policy': typeof AppPolicyRoute
  '/_app/views': typeof AppViewsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/_app/issues/': typeof AppIssuesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/policy'
    | '/views'
    | '/issues/$issueId'
    | '/projects/$projectId'
    | '/teams/$teamId'
    | '/issues/'
    | '/projects/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/inbox'
    | '/policy'
    | '/views'
    | '/'
    | '/issues/$issueId'
    | '/projects/$projectId'
    | '/teams/$teamId'
    | '/issues'
    | '/projects'
    | '/teams'
  id:
    | '__root__'
    | '/_app'
    | '/_app/inbox'
    | '/_app/policy'
    | '/_app/views'
    | '/_app/'
    | '/_app/issues/$issueId'
    | '/_app/projects/$projectId'
    | '/_app/teams/$teamId'
    | '/_app/issues/'
    | '/_app/projects/'
    | '/_app/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy': {
      id: '/_app/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof AppPolicyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/views': {
      id: '/_app/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof AppViewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issues/': {
      id: '/_app/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof AppIssuesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issues/$issueId': {
      id: '/_app/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof AppIssuesIssueIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId': {
      id: '/_app/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInboxRoute: typeof AppInboxRoute
  AppPolicyRoute: typeof AppPolicyRoute
  AppViewsRoute: typeof AppViewsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppIssuesIssueIdRoute: typeof AppIssuesIssueIdRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRoute
  AppIssuesIndexRoute: typeof AppIssuesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInboxRoute: AppInboxRoute,
  AppPolicyRoute: AppPolicyRoute,
  AppViewsRoute: AppViewsRoute,
  AppIndexRoute: AppIndexRoute,
  AppIssuesIssueIdRoute: AppIssuesIssueIdRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppTeamsTeamIdRoute: AppTeamsTeamIdRoute,
  AppIssuesIndexRoute: AppIssuesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
