/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAutomationRouteRouteImport } from './routes/_app/automation/route'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppPolicyRouteImport } from './routes/_app/policy'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppValidatorRouteImport } from './routes/_app/validator'
import { Route as AppViewsRouteImport } from './routes/_app/views'
import { Route as AppAutomationIndexRouteImport } from './routes/_app/automation/index'
import { Route as AppAutomationIntegrationsRouteImport } from './routes/_app/automation/integrations'
import { Route as AppAutomationRulesRouteImport } from './routes/_app/automation/rules'
import { Route as AppAutomationSkillsRouteImport } from './routes/_app/automation/skills'
import { Route as AppAutomationValidatorRouteImport } from './routes/_app/automation/validator'
import { Route as AppIssuesIndexRouteImport } from './routes/_app/issues/index'
import { Route as AppIssuesIssueIdRouteImport } from './routes/_app/issues/$issueId'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AppTeamsTeamIdRouteImport } from './routes/_app/teams/$teamId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRouteRoute = AppAutomationRouteRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyRoute = AppPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppValidatorRoute = AppValidatorRouteImport.update({
  id: '/validator',
  path: '/validator',
  getParentRoute: () => AppRoute,
} as any)
const AppViewsRoute = AppViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationIndexRoute = AppAutomationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAutomationRouteRoute,
} as any)
const AppAutomationIntegrationsRoute =
  AppAutomationIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppAutomationRouteRoute,
  } as any)
const AppAutomationRulesRoute = AppAutomationRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppAutomationRouteRoute,
} as any)
const AppAutomationSkillsRoute = AppAutomationSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppAutomationRouteRoute,
} as any)
const AppAutomationValidatorRoute = AppAutomationValidatorRouteImport.update({
  id: '/validator',
  path: '/validator',
  getParentRoute: () => AppAutomationRouteRoute,
} as any)
const AppIssuesIndexRoute = AppIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesIssueIdRoute = AppIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/automation': typeof AppAutomationRouteRouteWithChildren
  '/inbox': typeof AppInboxRoute
  '/integrations': typeof AppIntegrationsRoute
  '/policy': typeof AppPolicyRoute
  '/rules': typeof AppRulesRoute
  '/skills': typeof AppSkillsRoute
  '/validator': typeof AppValidatorRoute
  '/views': typeof AppViewsRoute
  '/automation/integrations': typeof AppAutomationIntegrationsRoute
  '/automation/rules': typeof AppAutomationRulesRoute
  '/automation/skills': typeof AppAutomationSkillsRoute
  '/automation/validator': typeof AppAutomationValidatorRoute
  '/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/automation/': typeof AppAutomationIndexRoute
  '/issues/': typeof AppIssuesIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/teams/': typeof AppTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/inbox': typeof AppInboxRoute
  '/integrations': typeof AppIntegrationsRoute
  '/policy': typeof AppPolicyRoute
  '/rules': typeof AppRulesRoute
  '/skills': typeof AppSkillsRoute
  '/validator': typeof AppValidatorRoute
  '/views': typeof AppViewsRoute
  '/': typeof AppIndexRoute
  '/automation/integrations': typeof AppAutomationIntegrationsRoute
  '/automation/rules': typeof AppAutomationRulesRoute
  '/automation/skills': typeof AppAutomationSkillsRoute
  '/automation/validator': typeof AppAutomationValidatorRoute
  '/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/automation': typeof AppAutomationIndexRoute
  '/issues': typeof AppIssuesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/teams': typeof AppTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/automation': typeof AppAutomationRouteRouteWithChildren
  '/_app/inbox': typeof AppInboxRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/policy': typeof AppPolicyRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/validator': typeof AppValidatorRoute
  '/_app/views': typeof AppViewsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/automation/integrations': typeof AppAutomationIntegrationsRoute
  '/_app/automation/rules': typeof AppAutomationRulesRoute
  '/_app/automation/skills': typeof AppAutomationSkillsRoute
  '/_app/automation/validator': typeof AppAutomationValidatorRoute
  '/_app/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/_app/automation/': typeof AppAutomationIndexRoute
  '/_app/issues/': typeof AppIssuesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/inbox'
    | '/integrations'
    | '/policy'
    | '/rules'
    | '/skills'
    | '/validator'
    | '/views'
    | '/automation/integrations'
    | '/automation/rules'
    | '/automation/skills'
    | '/automation/validator'
    | '/issues/$issueId'
    | '/projects/$projectId'
    | '/teams/$teamId'
    | '/automation/'
    | '/issues/'
    | '/projects/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/inbox'
    | '/integrations'
    | '/policy'
    | '/rules'
    | '/skills'
    | '/validator'
    | '/views'
    | '/'
    | '/automation/integrations'
    | '/automation/rules'
    | '/automation/skills'
    | '/automation/validator'
    | '/issues/$issueId'
    | '/projects/$projectId'
    | '/teams/$teamId'
    | '/automation'
    | '/issues'
    | '/projects'
    | '/teams'
  id:
    | '__root__'
    | '/_app'
    | '/_app/automation'
    | '/_app/inbox'
    | '/_app/integrations'
    | '/_app/policy'
    | '/_app/rules'
    | '/_app/skills'
    | '/_app/validator'
    | '/_app/views'
    | '/_app/'
    | '/_app/automation/integrations'
    | '/_app/automation/rules'
    | '/_app/automation/skills'
    | '/_app/automation/validator'
    | '/_app/issues/$issueId'
    | '/_app/projects/$projectId'
    | '/_app/teams/$teamId'
    | '/_app/automation/'
    | '/_app/issues/'
    | '/_app/projects/'
    | '/_app/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation': {
      id: '/_app/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AppAutomationRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy': {
      id: '/_app/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof AppPolicyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/validator': {
      id: '/_app/validator'
      path: '/validator'
      fullPath: '/validator'
      preLoaderRoute: typeof AppValidatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/views': {
      id: '/_app/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof AppViewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation/': {
      id: '/_app/automation/'
      path: '/'
      fullPath: '/automation/'
      preLoaderRoute: typeof AppAutomationIndexRouteImport
      parentRoute: typeof AppAutomationRouteRoute
    }
    '/_app/automation/integrations': {
      id: '/_app/automation/integrations'
      path: '/integrations'
      fullPath: '/automation/integrations'
      preLoaderRoute: typeof AppAutomationIntegrationsRouteImport
      parentRoute: typeof AppAutomationRouteRoute
    }
    '/_app/automation/rules': {
      id: '/_app/automation/rules'
      path: '/rules'
      fullPath: '/automation/rules'
      preLoaderRoute: typeof AppAutomationRulesRouteImport
      parentRoute: typeof AppAutomationRouteRoute
    }
    '/_app/automation/skills': {
      id: '/_app/automation/skills'
      path: '/skills'
      fullPath: '/automation/skills'
      preLoaderRoute: typeof AppAutomationSkillsRouteImport
      parentRoute: typeof AppAutomationRouteRoute
    }
    '/_app/automation/validator': {
      id: '/_app/automation/validator'
      path: '/validator'
      fullPath: '/automation/validator'
      preLoaderRoute: typeof AppAutomationValidatorRouteImport
      parentRoute: typeof AppAutomationRouteRoute
    }
    '/_app/issues/': {
      id: '/_app/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof AppIssuesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issues/$issueId': {
      id: '/_app/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof AppIssuesIssueIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId': {
      id: '/_app/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAutomationRouteRouteChildren {
  AppAutomationIntegrationsRoute: typeof AppAutomationIntegrationsRoute
  AppAutomationRulesRoute: typeof AppAutomationRulesRoute
  AppAutomationSkillsRoute: typeof AppAutomationSkillsRoute
  AppAutomationValidatorRoute: typeof AppAutomationValidatorRoute
  AppAutomationIndexRoute: typeof AppAutomationIndexRoute
}

const AppAutomationRouteRouteChildren: AppAutomationRouteRouteChildren = {
  AppAutomationIntegrationsRoute: AppAutomationIntegrationsRoute,
  AppAutomationRulesRoute: AppAutomationRulesRoute,
  AppAutomationSkillsRoute: AppAutomationSkillsRoute,
  AppAutomationValidatorRoute: AppAutomationValidatorRoute,
  AppAutomationIndexRoute: AppAutomationIndexRoute,
}

const AppAutomationRouteRouteWithChildren =
  AppAutomationRouteRoute._addFileChildren(AppAutomationRouteRouteChildren)

interface AppRouteChildren {
  AppAutomationRouteRoute: typeof AppAutomationRouteRouteWithChildren
  AppInboxRoute: typeof AppInboxRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppPolicyRoute: typeof AppPolicyRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppValidatorRoute: typeof AppValidatorRoute
  AppViewsRoute: typeof AppViewsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppIssuesIssueIdRoute: typeof AppIssuesIssueIdRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRoute
  AppIssuesIndexRoute: typeof AppIssuesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationRouteRoute: AppAutomationRouteRouteWithChildren,
  AppInboxRoute: AppInboxRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppPolicyRoute: AppPolicyRoute,
  AppRulesRoute: AppRulesRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppValidatorRoute: AppValidatorRoute,
  AppViewsRoute: AppViewsRoute,
  AppIndexRoute: AppIndexRoute,
  AppIssuesIssueIdRoute: AppIssuesIssueIdRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppTeamsTeamIdRoute: AppTeamsTeamIdRoute,
  AppIssuesIndexRoute: AppIssuesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
